### ISSUE TITLE
Provide support for running a KSQL script on Log Analytics

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1076]
Provide support for running a KSQL script on Log Analytics and report the metric.

This can be used for edge-cases where metrics are not in Azure Monitor but surfaced in Log Analtyics, for example https://github.com/tomkerkhove/promitor/discussions/1042

**Comment by tranmonglong0611** [comment]
Hi @tomkerkhove . I would like to contribute to this issue to solve our problems here #2117 . I have a question that the library you used for promitor https://github.com/Azure/azure-libraries-for-net seem to be deprecated. And it doesn't have API to query the log analytics also. 

So should I use the new azure sdk https://github.com/Azure/azure-sdk-for-net/tree/Azure.Monitor.Query_1.1.0/sdk/monitor/Azure.Monitor.Query/ for this new feature or is there any better way to do it ?

**Comment by tomkerkhove** [comment]
I thought I had an issue open for that migration but apparently not, so here it is https://github.com/tomkerkhove/promitor/issues/2127

However, this will not be a trivial thing as we'll need to make sure everything is still working.

Is this something you want to pick up before this issue?

**Comment by tomkerkhove** [comment]
Another idea might be to introduce the new SDK for this scraper next to the current one as a first step but I don't know what the impact/implications of it would be.

**Comment by tranmonglong0611** [comment]
> Another idea might be to introduce the new SDK for this scraper next to the current one as a first step but I don't know what the impact/implications of it would be.

I think I will go with this option first. I think I will need to create new Promitor.Integration.AzureLogAnalytics class which will use new sdk for everything like authen, query ...

**Comment by tomkerkhove** [comment]
That sounds good to me, thank you!

**Comment by tomkerkhove** [comment]
Closed in https://github.com/tomkerkhove/promitor/pull/2132
