### ISSUE TITLE
Reporting metrics based on ongoing timeseries for Azure File Storage

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1097]
Promitor is not respecting time series that are still running causing it to report invalid values.

For example, Azure File Storage was reporting `null` when aggregation was 1h because it reporting a timeseries that was only started.

**Comment by kad-beumer** [comment]
It seem like there are still issue's. Below graph show there is no data with certain intervals. The graph shows a timerange of 6 hours.

![image](https://user-images.githubusercontent.com/62944329/85106208-1b901300-b20c-11ea-8517-1420a02f253b.png)

**Comment by tomkerkhove** [comment]
I'll try to repro it again myself, sorry about that. I'm going to see if this is us or them because we can't do a lot more than this I'm afraid.

**Comment by tomkerkhove** [comment]
Looks like I can reproduce it, still. This is a nasty one and I'm not sure if it's just Promitor or Azure Storage metrics :(

**Comment by tomkerkhove** [comment]
This doesn't look good as well:
![image](https://user-images.githubusercontent.com/4345663/85149537-b3642000-b251-11ea-879c-fbfcacbbd261.png)

Are you seeing this in the Metric explorer as well @kad-beumer? Make sure to put aggregation to 1 hour.

**Comment by adamconnelly** [comment]
Just out of curiosity, is this the same issue that we were discussing in https://github.com/tomkerkhove/promitor/issues/711, or is it different?

**Comment by kad-beumer** [comment]
@tomkerkhove 

I'm seeing same results in Metric Explorer. Aggregation is set to 1 hour.

![image](https://user-images.githubusercontent.com/62944329/85511449-eb27ea80-b5f8-11ea-9033-258212d45140.png)

**Comment by tomkerkhove** [comment]
Hm that's not good. Are you ok with keeping this open until this is fixed in Azure Monitor? I'm afraid we can't do much about this :/

**Comment by kad-beumer** [comment]
No problem with me.

**Comment by tomkerkhove** [comment]
Thanks for your understanding and sorry for the inconvenience :(

**Comment by tomkerkhove** [comment]
> Just out of curiosity, is this the same issue that we were discussing in #711, or is it different?

I think in this case it's because of the storage metrics and noticed that we don't report finalized time series information (#1098) but the issue from #711 remains; although #1098 might fix that but I'm not sure if that's the correct approach.

**Comment by adamconnelly** [comment]
Thanks for the update Tom. It sounds promising anyway. Either way I guess we'll learn something!

**Comment by tomkerkhove** [comment]
Can this be closed @kad-beumer ?

**Comment by tomkerkhove** [comment]
Closing but feel free to re-open @kad-beumer
