### ISSUE TITLE
Introduce code tour which explains how to contribute a new scraper

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1111]
Introduce code tour which explains the steps that have to be taken to contribute a new scraper.

### Resources

- [CodeTour VSCode extension allows you to produce interactive guides, assessments and tutorials](https://techcommunity.microsoft.com/t5/educator-developer-blog/codetour-vscode-extension-allows-you-to-produce-interactive/ba-p/1274297)
- [CodeTour extension](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour)
- [Example repo](https://github.com/anthonychu/azure-functions-deno-template)

Follow-up of #1110

**Comment by adamconnelly** [comment]
@tomkerkhove I've started to take a look at this - do you want to assign it to me? I'm taking a look at it before the code spaces issue because it seemed pretty simple to do without having to setup code spaces yet.

**Comment by tomkerkhove** [comment]
Thanks mate!
