### ISSUE TITLE
Can't scrape SQL databases

### ISSUE THREAD

**Issue by renebarbosafl** [tomkerkhove/promitor#1238]
We're trying to scrape 2 Azure SQL databases, one of them is part of an Elastic Pool and the other one is not. The scrape is only working fine with the Elastic Pool Database and isn't working with the other.

## Expected Behavior

Get metrics from both databases

## Actual Behavior

Only got metrics from the database which is part of an Elastic Pool.

[22:59:00 INF] Scraping azure_sql_database_dtu_consumption_percent for resource type SqlDatabase
[22:59:01 INF] Found value null for metric azure_sql_database_dtu_consumption_percent with aggregation interval 00:05:00
[22:59:01 INF] Found value 2.5875 for metric azure_sql_database_dtu_consumption_percent with aggregation interval 00:05:00

We are getting 'null' from the other one.

## Steps to Reproduce the Problem

  1. Install Promitor
  2. Configure scrape
  3. Run

## Configuration

metrics:
  - name: azure_sql_database_dtu_consumption_percent
    description: "The DTU consumption percentage used by an Azure SQL Database"
    resourceType: SqlDatabase
    azureMetricConfiguration:
      metricName: dtu_used
      aggregation:
        type: Average
    resources:
    - serverName: elastic-prod1
      databaseName: superpratico-pe
      resourceGroupName: SuperPratico-Geral
    - serverName: elastic-prod1
      databaseName: superpratico-pb
      resourceGroupName: SuperPratico-Geral

## Specifications

  - Version: Docker image with the 'latest' tag
  - Platform: Linux
  - Subsystem:

**Comment by tomkerkhove** [comment]
Thanks for the report. Can you show me what the Metrics Explorer shows in the Azure portal for both please?

Normally we have `null` because the Azure Monitor API doesn't provide any info.

**Comment by renebarbosafl** [comment]
Yeah, you're right. For some reason we only have elastic-enabled databases with metrics on Azure Monitor. The other (single) databases are not showing there. That's weird.

**Comment by tomkerkhove** [comment]
Most probably that DB is idle for which they then don't emit metrics, is that possible?

Unfortunately there's not much we can do about it other than logging the default metric value that is configured. (see [`prometheusScrapingEndpoint.metricUnavailableValue` for Prometheus](https://promitor.io/configuration/v1.x/runtime#prometheus-scraping-endpoint))

**Comment by renebarbosafl** [comment]
That database is in production and is under considerable load (checking via SQL Server Management Studio). 
It looks like a bug in Azure Monitor.. We'll open a ticket with Microsoft to check on this.

Thanks Tom!

**Comment by tomkerkhove** [comment]
Thank you for checking in and using Promitor! Feel free to let us know if we can [list you as a customer](https://forms.gle/hjcpaaVFa1A1hZaK6).

**Comment by renebarbosafl** [comment]
Hi Tom,

We updated the form with our company information and logo.We kindly ask you
to inform us if (and when) our logo will be shown on your website. Our
marketing team will love to check on it.

Regards,
Renê Barbosa de F. Lima


Em seg., 24 de ago. de 2020 às 11:31, Tom Kerkhove <notifications@github.com>
escreveu:
