### ISSUE TITLE
Can't filter or view by dimensions which include / in name

### ISSUE THREAD

**Issue by renebarbosafl** [tomkerkhove/promitor#1248]
When using generic scraper to check Azure Application Insights metrics we can't filter or view metrics using dimensions. If we filter, the filter declaration is ignored and if we declare a dimension, the scrap isn't working.

## Expected Behavior

Scrap metrics or filter them based in dimension using Generic scraper and Application Insights.

## Actual Behavior

If using filter we got the same value from both scraps:

[14:01:10 INF] Found value 30.64830964005684 for metric azure_app_insights_bioserver_response_time with aggregation interval 00:30:00
[14:01:10 INF] Found value 30.64830964005684 for metric azure_app_insights_bioserver_response_time with aggregation interval 00:30:00

If using dimension, the scrap is not working:

[23:42:32 FTL] Failed to scrape resource for metric 'integrations_perf_detranal'
System.ArgumentException: Label name must match regex: ^[a-zA-Z_:][a-zA-Z0-9_:]*$
   at Prometheus.Client.MetricConfiguration..ctor(String name, String help, Boolean includeTimestamp, Boolean suppressEmptySamples, IReadOnlyList`1 labels)
   at Prometheus.Client.MetricFactory.CreateGauge(String name, String help, Boolean includeTimestamp, Boolean suppressEmptySamples, String[] labelNames)
   at Promitor.Integrations.Sinks.Prometheus.PrometheusMetricWriter.ReportMetric(PrometheusMetricDefinition metricDefinition, ScrapeResult scrapedMetricResult) in /src/Promitor.Integrations.Sinks.Prometheus/PrometheusMetricWriter.cs:line 36
   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 77

## Steps to Reproduce the Problem

  1. Configure generic scrap methor to check Application Insights object
  2. Filter some metrics using "filter" or "dimension"
  3. Check the logs

## Configuration

Not filtering:
 - name: integrations_perf_detranal
    description: "just a test"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      aggregation:
        type: Average
    resources:
    - resourceUri: Microsoft.Insights/Components/AL-Insights-API
      filter: dependency/target eq 'address1.tld'
    - resourceUri: Microsoft.Insights/Components/AL-Insights-API
      filter: dependency/target eq 'address2.tld'

Error:
 - name: integrations_perf_detranal
    description: "just a test"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      dimension:
        name: dependency/target
      aggregation:
        type: Average
    resources:
    - resourceUri: Microsoft.Insights/Components/AL-Insights-API
      resourceGroupName: SuperPratico-AL

**Comment by renebarbosafl** [comment]
Using this yaml:

- name: azure_trafficmanager_node_count
    description: "Traffic Manager node count"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: ProbeAgentCurrentEndpointStateByProfileResourceId
      dimension:
        name: EndpointName
      aggregation:
        type: Maximum
    resources:
    - resourceUri: Microsoft.Network/trafficManagerProfiles/bioservergpu
      resourceGroupName: SuperPratico-Geral

We got the following result (subscriptions ids were manually edited for security reasons):

# HELP azure_trafficmanager_node_count Traffic Manager node count
# TYPE azure_trafficmanager_node_count gauge
azure_trafficmanager_node_count{resource_group="SuperPratico-Geral",subscription_id="signature",resource_uri="subscriptions/signature/resourceGroups/SuperPratico-Geral/providers/Microsoft.Network/trafficManagerProfiles/bioservergpu",instance_name="Microsoft.Network/trafficManagerProfiles/bioservergpu",endpointname="bioservergpu2"} 1
azure_trafficmanager_node_count{resource_group="SuperPratico-Geral",subscription_id="signature",resource_uri="subscriptions/signature/resourceGroups/SuperPratico-Geral/providers/Microsoft.Network/trafficManagerProfiles/bioservergpu",instance_name="Microsoft.Network/trafficManagerProfiles/bioservergpu",endpointname="bioservergpu1"} 1


So i think the whole issue is the character / used in Application Insights metrics and dimensions.

**Comment by tomkerkhove** [comment]
This is fixed and available in next preview.

You can use this image until then https://github.com/tomkerkhove/promitor/pull/1253#issuecomment-683754171.

**Comment by renebarbosafl** [comment]
Hi Tom, 

This image is not starting. The error is:

System.InvalidOperationException: Unable to resolve service for type 'Prometheus.Client.Abstractions.IMetricFactory' while attempting to activate 'Promitor.Integrations.Sinks.Prometheus.RuntimeMetricsCollector'.

Using the 'latest' image from repo the container is starting fine with the same yaml files.

Regards,

**Comment by tomkerkhove** [comment]
Can you elaborate on which latest tag on which image please? Sorry for the inconvenience with the PR image, look in to it soon.

**Comment by renebarbosafl** [comment]
The image tomkerkhove/promitor-agent-scraper:latest is running fine.

With the image tomkerkhove/promitor-agent-scraper-ci:pr1253-linux we got the error below:
System.InvalidOperationException: Unable to resolve service for type 'Prometheus.Client.Abstractions.IMetricFactory' while attempting to activate 'Promitor.Integrations.Sinks.Prometheus.RuntimeMetricsCollector'.

Both with the same yaml configuration files.

**Comment by tomkerkhove** [comment]
Hm so you are saying that it displays the metric with latest tag on that image.

Odd, it's not shipped yet so will have to look into that.

**Comment by renebarbosafl** [comment]
Hi Tom, 

I got this working by fixing the 'runtime.yaml' file. Thanks!
Now we can use dimensions but we still can't filter. Example:

`  - name: azure_app_insights_api_depend_fail
    description: "Web Application Dependency Failures"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/failed
      dimension:
        name: dependency/target
      aggregation:
        type: Count
    resources:
    - resourceUri: Microsoft.Insights/Components/GO-Insights-API
      filter: 'dependency/resultCode eq 500'
      resourceGroupName: SuperPratico-GO
`
Expected behavior: We want to exclude 4xx result codes and only store 5xx. 
Current behavior: Everything is being stored.

**Comment by tomkerkhove** [comment]
Created #1266 for this, I'll see if I can figure it out.
