### ISSUE TITLE
Provide support for scraping metrics for Azure ExpressRoute circuits

### ISSUE THREAD

**Issue by bluepixbe** [tomkerkhove/promitor#1251]
Provide support for scraping metrics for Azure ExpressRoute circuits

If you are fine I think I could soon push a PR for that.

**Comment by tomkerkhove** [comment]
That's a fair ask and I'm more than happy to review a PR!

We have some docs on how [to contribute](https://github.com/tomkerkhove/promitor/blob/master/development-guide.md) and [how to add a new scraper](https://github.com/tomkerkhove/promitor/blob/master/adding-a-new-scraper.md).

**Comment by bluepixbe** [comment]
@tomkerkhove cool. Thanks for the links. 

Code/docs should be ready. Tests are looking good and the metrics were properly collected.

The only issue I face now while pushing the branch is a 403.. Will try to check tomorrow.

**Comment by tomkerkhove** [comment]
Thanks! Normally that's because you try to push to this repo instead of your fork? Can you check please?

**Comment by bluepixbe** [comment]
@tomkerkhove Thanks for your hint. But I had somehow a mess with my git credentials (private & corporate users) in the windows credentials manager. Finally it worked. I pushed it with the wrong user but that doesn't matter ;)
