### ISSUE TITLE
Provide support for scraping metrics for Azure Network Gateway

### ISSUE THREAD

**Issue by bluepixbe** [tomkerkhove/promitor#1264]
Provide support for scraping metrics for Azure Network Gateways

**Comment by tomkerkhove** [comment]
I'm new to Azure Network Gateway and can't seem to find much docs about it. Are VPN gateways a superset of this or are they the same?

**Comment by bluepixbe** [comment]
@tomkerkhove Sry, for my late reply. I was 2 weeks away. Will try to finish this PR this week.

Regarding your question. The whole service is called virtual network gateway. When provisioning you choose if it's from type VPN or ExpressRoute.

**Comment by tomkerkhove** [comment]
Ha, thanks for the heads up! So this scraper would work for both VPN & ExpressRoute then or do they have different flavors (and thus different scrapers)?

**Comment by bluepixbe** [comment]
@tomkerkhove Yes, exactly that's the same. The determination if it's for VPN or ExpressRoute is a simple attribute on the Network Gateway where you then have different attributes based on the chosen type but the metrics are the same.

**Comment by tomkerkhove** [comment]
Thanks! In that case the current PR is ok and I'll review it; might add convenient scraper types which uses that logic though to make it easier to discovery.
