### ISSUE TITLE
Filtering by dimensions which include / in name does not work in generic scraper

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1266]
Filtering by dimensions which include / in name does not work as reported in https://github.com/tomkerkhove/promitor/issues/1248#issuecomment-687727795 by @renebarbosafl:

> Example:
> 
> ```yaml
> - name: azure_app_insights_api_depend_fail
>     description: "Web Application Dependency Failures"
>     resourceType: Generic
>     azureMetricConfiguration:
>       metricName: dependencies/failed
>       dimension:
>         name: dependency/target
>       aggregation:
>         type: Count
>     resources:
>     - resourceUri: Microsoft.Insights/Components/Insights-API
>       filter: 'dependency/resultCode eq 500'
>       resourceGroupName: ResourceGroup`
> ```
> 
> Expected behavior: We want to exclude 4xx result codes and only store 5xx.
> Current behavior: Everything is being stored (Filter is being ignored).

**Comment by tomkerkhove** [comment]
Might be because 500 needs to be '500' in the filter by will verify

**Comment by renebarbosafl** [comment]
Thank you!
@tomkerkhove I've also tried with '500' and the same behavior is seen (not filtering).

Another question: Is it possible to filter multiple resultcodes? 
We want to do something like this (attached).
![Captura de tela de 2020-09-06 08-02-54](https://user-images.githubusercontent.com/70078638/92324360-65241900-f017-11ea-8346-5176359e0021.png)

**Comment by tomkerkhove** [comment]
I'm checking with Microsoft how to query it because the API does not like the `/`.

I've added #1269 for your multiple filters but it will not be in 2.0, sorry about that.
You can add different metrics for those as a workaround although it's not nice.
