### ISSUE TITLE
Deployment page URLs point to missing pages

### ISSUE THREAD

**Issue by JanneKataja-TomTom** [tomkerkhove/promitor#1300]
URLs on the deployment website page are incorrect or point to missing pages.

## Expected Behavior
Deploying documentation is shown

## Actual Behavior
404 File not found

## Steps to Reproduce the Problem

  1. Go to  https://promitor.io/deployment/
  2. Click _Deploying Promitor Scraper_ or _Deploying Promitor Resource Discovery_

**Comment by tomkerkhove** [comment]
Thanks for letting me know! Where did you find this link?

**Comment by JanneKataja-TomTom** [comment]
You're welcome! I don't remember the exact place where I found it, but it's visible on Google, ie. search for: _Here is an overview of the Promitor agents you can deploy_

**Comment by tomkerkhove** [comment]
No problem, I'll add a redirect for it.

Feel free to let me know if you have other issues or contact me on kerkhove.tom@gmail.com. 

Thanks again!

**Comment by tomkerkhove** [comment]
This is fixed and available on https://promitor.io/deployment, thanks for the report!
