### ISSUE TITLE
Helm chart 1.6.0 runs container image 1.0.0

### ISSUE THREAD

**Issue by JanneKataja-TomTom** [tomkerkhove/promitor#1301]
Helm chart 1.6.0 starts Promitor scraping agent version 1.0.0 and not app version 1.6.1.

## Expected Behavior
Running Promitor version 1.6.x

## Actual Behavior
Running Promitor version 1.0.0

## Steps to Reproduce the Problem

Following the instructions to install Promitor scraping agent with AKS: https://promitor.io/walkthrough/scrape-promitor-with-prometheus-on-azure-kubernetes-service

  1. Add Promitor helm repository: `helm repo add promitor https://promitor.azurecr.io/helm/v1/repo` and `helm repo update`
  2. Install Promitor agent scraper using: `helm install promitor-agent-scraper promitor/promitor-agent-scraper  --values metric-declaration.yml`
  3. Observe using `helm list` that chart `promitor-agent-scraper-1.6.0` and app version 1.6.1 are deployed
  4. View running pod `kubectl describe pod promitor-agent-scraper-fcc7f4b4-jjtmn` and notice that container is running image `tomkerkhove/promitor-agent-scraper:1.0.0` that is version 1.0.0

In my case the logs showed exception from package `Promitor.Scraper.Host`, which is missing from project's sources  from the version tagged 1.6.0.

## Specifications

  - Version: Promitor 1.6.0
  - Platform: AKS 1.16.13
  - Subsystem: Helm v3.3.4

**Comment by JanneKataja-TomTom** [comment]
Helm chart version `2.0.0-preview-3` starts the matching scraper image `tomkerkhove/promitor-agent-scraper:2.0.0-preview-3`

**Comment by tomkerkhove** [comment]
Thanks I'll have a look at this ASAP. Feel free to use the preview as this will be finalized soon and is the way forward.

**Comment by tomkerkhove** [comment]
Closing as it is fixed in 2.0

**Comment by tomkerkhove** [comment]
This is available in https://github.com/tomkerkhove/promitor/releases/tag/helm-1.6.1 for those on Promitor 1.x.
