### ISSUE TITLE
[helm charts] Introduce `namespace: {{ .Release.Namespace }}` in objects metadata

### ISSUE THREAD

**Issue by blafry** [tomkerkhove/promitor#1358]
Ability to use the helm chart when having declarative definition of all cluster objects rendered using helm template, for example in tools like Spinnaker.

Solution - add in all namespace-scoped resource definitions:

```
metadata:
    namespace: {{ .Release.Namespace }}
```

For more context please look in this thread [bitnami/charts#2006](https://github.com/bitnami/charts/issues/2006)

Of course, I can prepare the appropriate PR.

**Comment by tomkerkhove** [comment]
Sure, feel free to send a PR! Thanks for the suggestion.

**Comment by blafry** [comment]
Thanks!
Here is [PR](https://github.com/tomkerkhove/promitor/pull/1359).
