### ISSUE TITLE
Helm chart doesn't handle automatic discovery for Prometheus & DNS loadbalancer well

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1398]
Helm chart doesn't handle automatic discovery for Prometheus & DNS load balancer well when configuring both.

## Expected Behavior

Both features are working.

## Actual Behavior

Public DNS for load balancer is misconfigured

**Comment by msftkenneth** [comment]
Is it possible to also include internal load balancer annotation?
Something like this
```  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"```

**Comment by tomkerkhove** [comment]
Sure, opened #1402 & #1403 for this
