### ISSUE TITLE
Provide support for liveness probe

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#143]
Provide support for liveness probes to verify that the scraping process is still active.

This should be done by checking the health endpoint. (#9)

This should be added to the Kubernetes spec we have to perform deployments.

**Comment by tomkerkhove** [comment]
Relates to #17 where it should be added to as well

**Comment by cnadolny** [comment]
Working on this

**Comment by tomkerkhove** [comment]
Closing as this was added via #457, thanks @cnadolny & @lee0c !
