### ISSUE TITLE
documentation - incorrect names for environment variables for Azure authentication

### ISSUE THREAD

**Issue by cscoon** [tomkerkhove/promitor#1491]
**Report**

The documentation located at: https://promitor.io/configuration/v2.x/azure-authentication.html incorrectly states that the environment variables holding the app ID and app key for authentication into Azure are PROMITOR_AUTH_APPID and PROMITOR_AUTH_APPKEY.

The correct values are AUTH_APPID and AUTH_APPKEY.  For reference: https://github.com/tomkerkhove/promitor/blob/master/src/Promitor.Core/EnvironmentVariables.cs

**Expected Behavior**

I expected the environment variables I created per documentation to prevent an exception from being thrown.

**Actual Behavior**

An exception was thrown.  (Sorry... but the "expected" and "actual" are required fields! :) )

**Steps to Reproduce the Problem**

See references above.

**Component**

Resource Discovery

**Version**

2.0.0

**Configuration**

_No response_

**Logs**

_No response_

**Platform**

Other

**Contact Details**

_No response_

asdf

**Comment by tomkerkhove** [comment]
The code you are referring to does not include the prefix.

Did you have issues at runtime? If so, can you share them please?

**Comment by cscoon** [comment]
Correct.  The code does NOT include the prefix.  The documentation in the link I provided DOES include the prefix.  

So the documented name of the environment variables does not match what the code is actually looking for.
