### ISSUE TITLE
Provide case invarient lookups for resource group filtering

### ISSUE THREAD

**Issue by cscoon** [tomkerkhove/promitor#1492]
**Proposal**

I created a resource declaration for CosmosDb using Azure resource groups for my criteria.  However, the Resource Discovery API did not return my CosmosDb instance.  After debugging, it appeared that the query that Resource Discovery was correct, so there didn't appear to be a bug in how the query was constructed.

After removing the criteria so I could get back all instances (including the one I was looking for), I could see that the resource group name that was returned with my CosmosDb was in all lower case.  In my resource declaration YAML, I had cased it exactly how it appeared in the Azure Portal - which meant a couple of caps and the rest lower case.

This is probably behavior coming from the Azure Resource Graph.  But since the resource declaration config exactly matched the Azure Portal, it wasn't obvious what the issue was.

It would be a great feature if the Resource Discovery bootstrap would put all of this into the casing that the Azure Resource Graph requires.  In my case, I caught it.  But if the query should have returned 43 instances and it only returned 42, it could have very well gone undetected.

**Component**

Resource Discovery

**Contact Details**

_No response_

**Comment by tomkerkhove** [comment]
Ha, good point. I didn't think about that, sorry!
