### ISSUE TITLE
documentation for using scraper with Resource Discovery is missing a critical setting

### ISSUE THREAD

**Issue by cscoon** [tomkerkhove/promitor#1495]
**Report**

I attempted to deploy the scraper and point it to my Resource Discovery deployment several times using the documentation, but it consistently failed.  This was the relevant config section I passed to the scraper helm chart:

resourceDiscovery:
  host: promitor-agent-resource-discovery.monitoring.svc.cluster.local
  port: 8889

Each time I deployed, the scraper pod went into CrashLoopBackOff status and wrote an error message in the log.  I've attached it to this issue.

After a lot of digging through the Promitor and Promitor chart repos, I found the issue - if the enabled: true property isn't included, it defaults to false, and Promitor scraper fails validation.

The problem is that not only does the documentation not mention that this property defaults to false, but the documentation I found doesn't even mention the existence of the 'resourceDiscovery.enabled' property at all, leading to several failed deployments.

The documentation should be updated to include this critical property.

Here are the documentation locations I found that show examples of 'resourceDiscovery:' configuration, but make no mention of the 'enabled' property.  Please note that there may be more locations that I didn't run across:

https://promitor.io/configuration/v2.x/runtime/scraper.html
https://promitor.io/configuration/v2.x/runtime/scraper.html

**Expected Behavior**

I expected the code samples in the documentation to include required fields for the scraper to run when it's configured to use Resource Discovery.

**Actual Behavior**

The code samples did not include the critical 'enabled' field, resulting in the pod going into CrashLoopBackOff status.

**Steps to Reproduce the Problem**

1. Deploy Resource Discovery.
2. Deploy the scraper, pointing to Resource Discovery, but without the 'enabled' property.
3. Scraper fails with attached error

**Component**

Scraper

**Version**

2.0.0

**Configuration**

Configuration:

```yaml
# Add your scraping configuration here
```

**Logs**

```shell
example
```

**Platform**

_No response_

**Contact Details**

_No response_

<img width="1629" alt="scraper error" src="https://user-images.githubusercontent.com/40893895/107234300-24c32f80-69e9-11eb-944c-ad59a7fe85f8.PNG">

**Comment by tomkerkhove** [comment]
Nice find, thanks!
