### ISSUE TITLE
Configurable limit for metrics with multiple dimensions

### ISSUE THREAD

**Issue by DaveOHenry** [tomkerkhove/promitor#1595]
### Proposal

I was wondering why Promitor does not deliver all metrics for some of our services. Looks like the default limit (at least in the portal) is 10:
![image](https://user-images.githubusercontent.com/20969773/115006142-d2026a00-9ea8-11eb-884b-45128f0f8c02.png)

Unfortunately I didn't find any configuration option for the limit in Promitor, therefore this feature request.

### Component

Scraper

**Comment by tomkerkhove** [comment]
Ha, interesting! So you always get 10 results and nothing more?

Good point, I'll try to figure it out.

**Comment by tomkerkhove** [comment]
Ideally you get everything most probably?

**Comment by DaveOHenry** [comment]
Promitor currently only shows the metrics for 10 backend pools from an Application Gateway instance, but there are over 30 pools.
It's most likely the default from Azure metrics api.

**Comment by tomkerkhove** [comment]
Makes sense, I'll test it that way - Thanks a lot!

**Comment by tomkerkhove** [comment]
Looks like an API parameter that we'll specify - https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list#uri-parameters

**Comment by tomkerkhove** [comment]
Ok, turns out we can configure it here:
https://github.com/tomkerkhove/promitor/blob/e1fdb945a79a0a58b20411f7288ef98cc8c1e6f7/src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs#L205-L209

I'll get started on this

**Comment by tomkerkhove** [comment]
I presume you don't want to configure the maximum amount or would you?

**Comment by DaveOHenry** [comment]
You mean just set the parameter to "maxint32" in the code? That would probably work, but I can imagine that there are edge cases where this is not desired. 
I think it's better to leave the choice to the user and maybe expose the parameter in the configuration under "Metric Defaults" if that makes sense.

**Comment by tomkerkhove** [comment]
I was thinking the same so that's perfect!

**Comment by tomkerkhove** [comment]
So this is what it would look like:
```diff
version: v1
azureMetadata:
  tenantId: ABC
  subscriptionId: XYZ
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
  labels:
    geo: china
    environment: dev
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
 - name: promitor_demo_servicebus_messagecount_discovered
  description: "Average percentage of memory usage on an Azure App Plan"
  resourceType: ServiceBusNamespace
  labels:
    geo: europe
    app: promitor
  azureMetricConfiguration:
    metricName: ActiveMessages
+   limit: 100 # Default: 10 000
    aggregation:
      type: Average
  resources:
  - namespace: promitor-messaging
```

What do you think? I didn't add it to `metricDefaults` for now since the new default is 10 000 unless you'd like to use that, then it would be:

```diff
version: v1
azureMetadata:
  tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
  subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
  resourceGroupName: promitor
metricDefaults:
+ limit: 100 # Default: None
  aggregation:
    interval: 00:05:00
  labels:
    geo: china
    environment: dev
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
 - name: promitor_demo_servicebus_messagecount_discovered
  description: "Average percentage of memory usage on an Azure App Plan"
  resourceType: ServiceBusNamespace
  labels:
    geo: europe
    app: promitor
  azureMetricConfiguration:
    metricName: ActiveMessages
+   limit: 1000 # Default: 10 000
    aggregation:
      type: Average
  resources:
  - namespace: promitor-messaging
```

**Comment by DaveOHenry** [comment]
This is an awesome improvement 😃 I'm always a little concerned with changing default values, but in this case it totally makes sense, because most users certainly expect Promitor to return all metrics.

**Comment by tomkerkhove** [comment]
Yes, that's the only reason why it's going up indeed.

Do you want the metric defaults or not perse?

**Comment by DaveOHenry** [comment]
A configurable limit in "metricDefaults" doesn't hurt, but I think most people will certainly never change this limit (myself included) 😉
