### ISSUE TITLE
Unable to find a required configuration file at '/config//runtime.yaml'

### ISSUE THREAD

**Issue by ashuw018** [tomkerkhove/promitor#1633]
### Report

I am trying shift from azure metrics exporter to Promitor.
I thought of give it a try on my Docker-Desktop, in my compose file I was already having prometheus and grafana working.
all are running in linux mode on windows 10 docker desktop.

I have added Promitor to compose like.
=========

  promitor:
    image: ghcr.io/tomkerkhove/promitor-agent-scraper:latest-linux
    container_name: promitor
    volumes:
      - ./promitor/runtime.yaml:/config/runtime.yaml
      - ./promitor/metrics-declaration.yaml:/config/metrics-declaration.yaml
    environment:
      - PROMITOR_AUTH_APPKEY=xxxxxxxx
      - PROMITOR_AUTH_APPID= xxxxxxxxxxxxxxx
      - PROMITOR_YAML_OVERRIDE_server__httpPort=80

    ports:
      - 8999:80
    networks:
      - monitor-net

====

Bothe the volume files are present on local but still in logs I receive.
[12:41:52 FTL] Unable to find a required configuration file at '/config//runtime.yaml'

I tried the docker run as well and getting same logs. I am doing same bind mounting for my prometheus and other components  in stack, dont know why it is not able to find the file.

### Expected Behavior

Container should work fine.

### Actual Behavior

getting error in logs
[12:41:52 FTL] Unable to find a required configuration file at '/config//runtime.yaml'

### Steps to Reproduce the Problem

Create docker compose on windows 10 docker-desktop
create local folder in pwd, and put runtime.yaml and metrics-declaration.yaml in it. then a=have you volume bind for respective yaml files to their respective yaml file. like

    volumes:
      - ./promitor/runtime.yaml:/config/runtime.yaml
      - ./promitor/metrics-declaration.yaml:/config/metrics-declaration.yaml

### Component

Scraper

### Version

v2.0.0-rc

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

### Logs

```shell
example
```

### Platform

Other

### Contact Details

ashuw018@gmail.com

**Comment by tomkerkhove** [comment]
Hi, are you sure that the file is actually mounted and contains the correct data?

For example, what does a `cat /config/runtime.yaml` give you?

PS: It would be recommended to use a newer version than 2.0-rc

**Comment by tomkerkhove** [comment]
@ashuw018 Is this still the case?

**Comment by tomkerkhove** [comment]
Closing due to inactive
