### ISSUE TITLE
Issue template for security-related reports

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#168]
Provide an issue template for security-related reports such as vulnerabilities.

**Comment by Hekku2** [comment]
Would following template contain expected information? [Security_issue.md](https://github.com/Hekku2/promitor/blob/patch-1/.github/ISSUE_TEMPLATE/Security_issue.md)

**Comment by tomkerkhove** [comment]
Sure, looks good to me. Feel free to PR a version that is aligned with the existing ones.

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________
