### ISSUE TITLE
Provide Kubernetes Helm Chart

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#17]
Provide Kubernetes Helm Chart to streamline deployments

**Comment by tomkerkhove** [comment]
We can host our custom Helm chart on Codefresh - https://codefresh.io/features/#Helm

**Comment by lee0c** [comment]
Working on this: @cnadolny @immuzz @lee0c

**Comment by tomkerkhove** [comment]
I've released a preview which is using the new image name: https://github.com/tomkerkhove/promitor/releases/tag/1.0.0-preview-1

**Comment by tomkerkhove** [comment]
Thanks @cnadolny & @lee0c !
