### ISSUE TITLE
Scrape metrics from multiple resource groups - selected RG not showing up

### ISSUE THREAD

**Issue by ayouba88** [tomkerkhove/promitor#1730]
Hello, 

I have an azure account with multiple subscribers, and each subscriber with multiple groups.
I have confguired a seperate scraper/discovery container per subscribers, and in the metrics file i confguired only one group for each subscriber.
tfter reviewing the data/metrics i see that the promitor is scraping from SEVERAL RGs, but it not scraping from the RG that i have specified in the metrics file

this is the RG that i have confguired --> rg-smartops-prod-att-management-atomiqtools

as you can see below, the promitor is scraping from several groups but not the group that i have confguired 
**all the groups are under same subscription

curl http://-----------:8900/metrics
# HELP active_connections Active Connections
# TYPE active_connections gauge
active_connections{resource_group="rg-smartops-prod-att-management-atomiqtools",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-atomiqtools/providers/Microsoft.DBforPostgreSQL/servers/testsqldb99",instance_name="testsqldb99"} 4 1629213482831
active_connections{resource_group="rg-smartops-prod-att-management-atomiqtools",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-atomiqtools/providers/Microsoft.DBforPostgreSQL/servers/psql-atomiq-finops-attmgmt",instance_name="psql-atomiq-finops-attmgmt"} 4 1629213480889
# HELP Availability The percentage of availability for the storage service or the specified API operation. Availability is calculated by taking the TotalBillableRequests value and dividing it by the number of applicable requests, including those that produced unexpected errors. All unexpected errors result in reduced availability for the storage service or the specified API operation.
# TYPE Availability gauge
Availability{resource_group="rg-smartops-prod-att-management-arcsight",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-arcsight/providers/Microsoft.Storage/storageAccounts/attmgmtarcsightlogger",instance_name="attmgmtarcsightlogger"} NaN 1629213427767
Availability{resource_group="rg-smartops-prod-att-management-devopsstorage1",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-devopsstorage1/providers/Microsoft.Storage/storageAccounts/attmgmtfilestorage01",instance_name="attmgmtfilestorage01"} NaN 1629213427907
# HELP azure_storage_accounts_used_capacity_average The amount of storage used by the storage account. For standard storage accounts, it's the sum of capacity used by blob, table, file, and queue. For premium storage accounts and Blob storage accounts, it is the same as BlobCapacity or FileCapacity.
# TYPE azure_storage_accounts_used_capacity_average gauge
azure_storage_accounts_used_capacity_average{resource_group="rg-smartops-prod-att-management-arcsight",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-arcsight/providers/Microsoft.Storage/storageAccounts/attmgmtarcsightlogger",instance_name="attmgmtarcsightlogger"} 400 1629213429086
azure_storage_accounts_used_capacity_average{resource_group="rg-smartops-prod-att-management-devopsstorage1",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-devopsstorage1/providers/Microsoft.Storage/storageAccounts/attmgmtfilestorage01",instance_name="attmgmtfilestorage01"} 232262595296 1629213428987
# HELP azur_virtual_machines_percentage_cpu_average Average percentage cpu usage on an Azure virtual machine
# TYPE azur_virtual_machines_percentage_cpu_average gauge
azur_virtual_machines_percentage_cpu_average{resource_group="rg-smartops-prod-att-management-atomiqtools",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-atomiqtools/providers/Microsoft.Compute/virtualMachines/atomiqmonitoringcatalog02-vm",instance_name="atomiqmonitoringcatalog02-vm"} 7.6295 1629213480992
azur_virtual_machines_percentage_cpu_average{resource_group="rg-smartops-prod-att-management-arcsight",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-arcsight/providers/Microsoft.Compute/virtualMachines/ATTmgmt-arc",instance_name="ATTmgmt-arc"} 1.1835 1629213421146
azur_virtual_machines_percentage_cpu_average{resource_group="rg-smartops-prod-att-management-identityvmgroup",subscription_id="d455cf74-85e8-4d74-8bde-195de1b940f7",resource_uri="subscriptions/d455cf74-85e8-4d74-8bde-195de1b940f7/resourceGroups/rg-smartops-prod-att-management-identityvmgroup/providers/Microsoft.Compute/virtualMachines/idmsrv-01",instance_name="idmsrv-01"} 0.55325 1629213425931

could you please suggest what can be the root cause ? 

Thanks and best regards

**Comment by tomkerkhove** [comment]
Hi, would it be possible to share your metrics declaration and resource discovery definition?
