### ISSUE TITLE
Provide unit tests for AzureResourceRepository

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1734]
Provide unit tests for AzureResourceRepository to verify the parsing of the resource graph responses and parsing.

[DiscoverAzureSubscriptionsAsync.json.txt](https://github.com/tomkerkhove/promitor/files/7009210/DiscoverAzureSubscriptionsAsync.json.txt)
[DiscoverAzureResourceGroupsAsync.json.txt](https://github.com/tomkerkhove/promitor/files/7009211/DiscoverAzureResourceGroupsAsync.json.txt)

**Comment by ashwin003** [comment]
Hello!
I would like to give this a shot if it is still available.

**Comment by tomkerkhove** [comment]
Awesome, thank you!
