### ISSUE TITLE
Resource is not discovering SqlServers

### ISSUE THREAD

**Issue by testskills** [tomkerkhove/promitor#1848]
### Report

We are interested in discovering and monitoring Azure SQL Server metrics. We are able to get SQL Databases metrics using below configuration.
- name: sql-database-landscape
  type: SqlDatabase

However we need to collect at Server level. We tried using

- name: sql-servers
  type: SqlServer

However this gives error. "Resource type 'SqlServer' for discovery group 'sql-servers' is not supported".

Looks like in the ResourceDiscoveryFactory we don't have configuration for SqlServer, although there is query class SqlServerDiscoveryQuery.

### Expected Behavior

Resource Discovery should be able to discover resource types as SqlServers.

### Actual Behavior

Error reported.
Resource type 'SqlServer' for discovery group 'sql-servers' is not supported.

### Steps to Reproduce the Problem

1. In the resource discovery configuration file configure below resource group.

- name: sql-servers
  type: SqlServer

2. Access API endpoint

http://127.0.0.1:8080/api/v1/resources/groups/sql-servers/discover

...

### Component

Resource Discovery

### Version

0.6.0

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

### Logs

```shell
example
```

### Platform

Microsoft Azure

### Contact Details

yjadhav@osisoft.com

**Comment by tomkerkhove** [comment]
Resource discovery for SQL Server is not supported yet as per the docs.

This is being tracked in https://github.com/tomkerkhove/promitor/issues/1129.

**Comment by tomkerkhove** [comment]
I'm open for contributions though - Are you willing to contribute it?

PS: If you are using Promitor in production, then I'm happy to list you as an end-user.

**Comment by testskills** [comment]
Thank you for your response @tomkerkhove .

We have just started exploring capabilities of Promitor. Definitely would like to contribute.

**Comment by tomkerkhove** [comment]
Awesome, thank you! I will close this one as a duplicate and feel free to ask questions if you need help with the contribution.
