### ISSUE TITLE
Helm install returns err pulling image:  x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by james-flynn-ie** [tomkerkhove/promitor#1867]
### Report

I'm deploying an existing configuration from a previous AKS cluster onto a new AKS cluster (the difference being that the new one uses the Azure network plugin instead of Kubenet).

The helm command completes, but the Pod returns an 'x509: certificate signed by unknown authority' when AKS attempts to pull the image.

Steps:
- helm install promitor-agent-scraper promitor/promitor-agent-scraper --values C:\repos\metric-declaration.yaml
-  kubectl get pods
```
promitor-agent-scraper-848485b64b-xdbk7     0/1     ErrImagePull   0          5s
```

- kubectl describe pod promitor-agent-scraper-848485b64b-xdbk7
```
...
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m19s                  default-scheduler  Successfully assigned default/promitor-agent-scraper-848485b64b-xdbk7 to aks-nodepool1-35682489-vmss000000
  Normal   Pulling    2m50s (x4 over 4m19s)  kubelet            Pulling image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1"
  Warning  Failed     2m49s (x4 over 4m18s)  kubelet            Failed to pull image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1": rpc error: code = Unknown desc = failed to pull and unpack image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1": failed to resolve reference "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1": failed to do request: Head "https://ghcr.io/v2/tomkerkhove/promitor-agent-scraper/manifests/2.5.1": x509: certificate signed by unknown authority
  Warning  Failed     2m49s (x4 over 4m18s)  kubelet            Error: ErrImagePull
  Normal   BackOff    2m36s (x6 over 4m17s)  kubelet            Back-off pulling image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1"
  Warning  Failed     2m21s (x7 over 4m17s)  kubelet            Error: ImagePullBackOff
```

Helm install has run successfully for other containers (e.g.: prometheus, grafana, ingress-nginx) which have successfully deployed as pods.

### Expected Behavior

Pod returns a 'Running' status following Helm install command. The `kubectl describe pod` reports that the image was successfully pulled and a container was started using the image.

### Actual Behavior

-  kubectl get pods
```
promitor-agent-scraper-848485b64b-xdbk7     0/1     ErrImagePull   0          5s
```

- kubectl describe pod promitor-agent-scraper-848485b64b-xdbk7
```
...
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m19s                  default-scheduler  Successfully assigned default/promitor-agent-scraper-848485b64b-xdbk7 to aks-nodepool1-35682489-vmss000000
  Normal   Pulling    2m50s (x4 over 4m19s)  kubelet            Pulling image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1"
  Warning  Failed     2m49s (x4 over 4m18s)  kubelet            Failed to pull image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1": rpc error: code = Unknown desc = failed to pull and unpack image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1": failed to resolve reference "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1": failed to do request: Head "https://ghcr.io/v2/tomkerkhove/promitor-agent-scraper/manifests/2.5.1": x509: certificate signed by unknown authority
  Warning  Failed     2m49s (x4 over 4m18s)  kubelet            Error: ErrImagePull
  Normal   BackOff    2m36s (x6 over 4m17s)  kubelet            Back-off pulling image "containers.promitor.io/tomkerkhove/promitor-agent-scraper:2.5.1"
  Warning  Failed     2m21s (x7 over 4m17s)  kubelet            Error: ImagePullBackOff
```

### Steps to Reproduce the Problem

1. helm install promitor-agent-scraper promitor/promitor-agent-scraper --values C:\repos\metric-declaration.yaml

### Component

Scraper

### Version

2.5.1

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

Same as walkthrough guide: https://docs.promitor.io/walkthrough/scrape-promitor-with-prometheus-on-azure-kubernetes-service.html

### Logs

```shell
example
```

N/A, doesn't get this far as it fails at the image pull stage. :)

### Platform

Microsoft Azure

**Comment by james-flynn-ie** [comment]
I also reached out to Microsoft support to rule out an AKS issue, and they replied that since it is related to an "unsigned cert issue", and they replied that they don't believe that there is much that they are able to do from their side.

"I have been checking the logs and there is not much we are able to do here, this is a third party product that complains about unsigned certificate when you are trying to install."

**Comment by tomkerkhove** [comment]
Sorry to hear and I'll have to dive into this.

In the meantime, can you try the using the ghcr.io/tomkerkhove/promitor-agent-scraper image instead please?

**Comment by tomkerkhove** [comment]
I have  tried to reproduce this but was unable to do so - Did you do anything special or have any security/network workloads that might interfere?

**Comment by james-flynn-ie** [comment]
Hi @tomkerkhove, thanks for looking into it and trying to reproduce the issue. It may very well be an issue with our firewalls interfering with the CA cert verification process.

As a workaround, I'll try pushing the image to Azure Container Registry and update the Helm chart to pull it from there, to see if that helps any.

**Comment by tomkerkhove** [comment]
Did this fix the issue for you?

**Comment by james-flynn-ie** [comment]
Thank you @tomkerkhove, apologies for the delay in replying. Yes, we should be good to close the ticket now. Thanks for your support. :+1:

**Comment by tomkerkhove** [comment]
Happy to help! Let's hope you are an exception :)
