### ISSUE TITLE
Link ACR docs to corresponding Azure Monitor section

### ISSUE THREAD

**Issue by pinowthebird** [tomkerkhove/promitor#1871]
### Report

The [Promitor docs about Azure Container Registry](https://docs.promitor.io/configuration/v2.x/metrics/container-registry.html) are stating that the Azure Monitor docs don't include anything on ACR. Instead, it's mentioning a [PR for the Azure Monitor docs](https://github.com/MicrosoftDocs/azure-docs/pull/27991).

That PR was closed in May '19 and the Azure Monitor docs now include ACR metrics: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerregistryregistries.

(PS: I had to select a `component` and `version`, but since this is about the docs, these are irrelevant. Let me know, if you want me to report this as another issue type.)

### Expected Behavior

[The Promitor docs about ACR](https://docs.promitor.io/configuration/v2.x/metrics/container-registry.html) should point to the [ACR anchor in the Azure Monitor docs](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerregistryregistries).

### Actual Behavior

[The Promitor docs about ACR](https://docs.promitor.io/configuration/v2.x/metrics/container-registry.html) are stating that the ACR metrics are not documented in the Azure Monitor docs.

### Steps to Reproduce the Problem

1. Open [the Promitor docs about ACR](https://docs.promitor.io/configuration/v2.x/metrics/container-registry.html)

### Component

Scraper

### Version

v2.x

**Comment by tomkerkhove** [comment]
Great to hear, thanks for letting me know! Are you willing to send a PR on this?

**Comment by pinowthebird** [comment]
@tomkerkhove Will do.
