### ISSUE TITLE
Ruby/EventMachine1.2.7 flagging as License issue

### ISSUE THREAD

**Issue by testskills** [tomkerkhove/promitor#1890]
### Report

We have run the black duck security scan and it came back with a blocker issue. For component "Ruby/EventMachine1.2.7" it is showing license as "GNU General Public License v2.0 only". We have policy to use Apache and MIT License only.  Although Promitor is MIT license, but these dependencies having GPL licenses could cause concerns as well.

Please suggest if anything can be done here.

### Affected Component(s)

Resource Discovery, Scraper

### Affected Version(s)

Scraper 2.5.1 / Resource Discovery 0.6.0

### Contact Details

yjadhav@osisoft.com

**Comment by tomkerkhove** [comment]
We only use Ruby for our documentation and not Promitor itself so you can ignore this.

**Comment by testskills** [comment]
Thank you for quick response!

**Comment by tomkerkhove** [comment]
Happy to help @testskills!
