### ISSUE TITLE
Write all telemetry to stdout and/or stderr

### ISSUE THREAD

**Issue by jdevalk2** [tomkerkhove/promitor#196]
### Specification

Currently exceptions and errors are logged to application insights. 

When running promitor in a docker container on Kubernetes, not everyone will want to configure application insights to see the logs.   Kubernetes standard is to log to stdout and errors to stderr.
From there on it can be picked up by any logging solution that is already running.

**Comment by tomkerkhove** [comment]
That's correct and as part of #29 our plan is to make this flexible to fit your needs.
However, stdout & stderr should be the least there is.

Thanks for suggesting this, should've been there already - My bad!

**Comment by tomkerkhove** [comment]
This is available in https://github.com/tomkerkhove/promitor/releases/tag/0.4.0
