### ISSUE TITLE
Provide unit tests for AzureResourceGroupsDiscoveryBackgroundJob

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#2052]
### Proposal

Provide unit tests for AzureResourceGroupsDiscoveryBackgroundJob to ensure we handle paging correctly.

### Component

Scraper

**Comment by MaurizioPz** [comment]
I would be happy to take this one if you want, can you assign it to me?

**Comment by tomkerkhove** [comment]
Great, thank you!
