### ISSUE TITLE
Service Bus Queue Metric Values are not correct 

### ISSUE THREAD

**Issue by RamyNasrEldin** [tomkerkhove/promitor#216]
The values I get from the library are not correct. I am trying to scrape metrics from Service Bus and the values I get is not like what I see in Azure portal.

## Expected Behavior
The values should match exactly the values I see in Azure portal in that specific time. 

## Actual Behavior
the values are not the same.

## Steps to Reproduce the Problem

  1. Add metric in the config map to get the Incoming messages average from service bus queue like below
    - name: usageimports_XXX_incomingmessages
      description: "Amount of incoming messages of the 'XXX' queue"
      resourceType: ServiceBusQueue
      namespace: NNN
      queueName: XXX
      azureMetricConfiguration:
        metricName: IncomingMessages
        aggregation: Average
  2. Run the application and check the coming value from that metric.
  3. compare the value with what you see in the azure portal in (Metrics section) use the same filtration used by the application. 

## Specifications

  - Version: latest
  - Platform: Windows

**Comment by tomkerkhove** [comment]
Can you please provide some more information like what you are seeing in the portal and what the output is of the scraping endpoint?

**Comment by tomkerkhove** [comment]
You've also tagged that it's for version `latest` which we don't have, can you be more specific please? Is it `0.3.0`?

**Comment by RamyNasrEldin** [comment]
Yes the version is 0.3.0

Regarding the values, let's take for instance the incoming messages, I attached screen shot from the portal for the metrics of one of the queues it contains 0 messages in the incoming messages. The scraped value shows 6.5

Note I did reviewed the code and I noticed that you are using utc timezone. My timezone is utc+1. but also when I changed it it still didn't work correctly. 
![portal](https://user-images.githubusercontent.com/34554820/48474430-d66b5a00-e7fa-11e8-9e98-80f5c91666c6.png)
![scrape](https://user-images.githubusercontent.com/34554820/48474432-d66b5a00-e7fa-11e8-90ec-14de9ab6bab2.png)

**Comment by tomkerkhove** [comment]
Thanks for sharing the information @RamyNasrEldin - Can you also provide your YAML configuration please?

**Comment by RamyNasrEldin** [comment]
Thanks @tomkerkhove for your response. Please find below config map.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promitor-scraper-metrics-config
  namespace: monitoring
data:
  # Provide your own version of the metric scraping declaration.
  # This version uses a sample.
  # See documentation for more information - https://promitor.io/configuration/metrics/
  metrics-declaration.yaml: |-
    azureMetadata:
      tenantId: ttt
      subscriptionId: xxx
      resourceGroupName: rrr
    metrics: 
        # v1.0
    - name: usageimports_rawdata_incomingRequests
      description: "Amount of incoming requests of the 't2s-usageimports-rawdata' queue"
      resourceType: ServiceBusQueue
      namespace: T2-UsageImport-DEV-WE
      queueName: t2s-usageimports-rawdata
      azureMetricConfiguration:
        metricName: IncomingRequests
        aggregation: Average
    - name: usageimports_rawdata_deadletteredMessages
      description: "Size of the 't2s-usageimports-rawdata' queue"
      resourceType: ServiceBusQueue
      namespace: T2-UsageImport-DEV-WE
      queueName: t2s-usageimports-rawdata
      azureMetricConfiguration:
        metricName: DeadletteredMessages
        aggregation: Average
    - name: usageimports_rawdata_incomingmessages
      description: "Amount of incoming messages of the 't2s-usageimports-rawdata' queue"
      resourceType: ServiceBusQueue
      namespace: T2-UsageImport-DEV-WE
      queueName: t2s-usageimports-rawdata
      azureMetricConfiguration:
        metricName: IncomingMessages
        aggregation: Average

**Comment by RamyNasrEldin** [comment]
Yes we are using the default scraping schedule.

**Comment by RamyNasrEldin** [comment]
Thanks, when I change the portal every 5 minutes is shows the numbers matched with the promitor output. 

I deployed promitor using Helm chart on my AKS cluster. everything seems to be working except there is no data appears in the endpoint "http://localhost:8080/prometheus/scrape" (note that I changed the port and I tested it by deploying container and it is working). As shown below when I do port forward it doesn't show anything at all 

![image](https://user-images.githubusercontent.com/34554820/48894408-fb874a80-ee42-11e8-96f0-e47f5b1cb93a.png)


the container doesn't show any error logs, please find some of the container logs below.

![image](https://user-images.githubusercontent.com/34554820/48894624-781a2900-ee43-11e8-8499-a137bf272d09.png)

do you know in which cases the promitor might do this case?

**Comment by tomkerkhove** [comment]
Good to hear that it's not because of a bug.

With helm chart, are you referring to this [YAML spec](https://github.com/tomkerkhove/promitor/blob/master/deploy/kubernetes-spec.yaml)?

If so, does this still match with your changes? Can you browse to the Swagger UI portal (`/swagger`)as well?

**Comment by tomkerkhove** [comment]
Closing this issue as it's not an issue. Feel free to re-open or create a new issue.
