### ISSUE TITLE
Metric labels for dimensions are missing in OpenTelemetry sink

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#2180]
### Expected Behavior

OpenTelemetry metrics should have labels for the dimensions being scraped

### Actual Behavior

Metric labels, default labels nor custom labels are available

### Steps to Reproduce the Problem

Scrape metrics with dimension

### Component

Scraper

### Version

2.8.0

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

### Logs

```shell
example
```

**Comment by amirschw** [comment]
They are also missing for StatsD, but I guess there's no need for another issue since #2183 should fix it for both

**Comment by tomkerkhove** [comment]
Correct!

**Comment by amirschw** [comment]
Just noticed the cool [end-user:msft-defender](https://github.com/tomkerkhove/promitor/issues?q=is%3Aopen+label%3Aend-user%3Amsft-defender) label. Can we add it to this issue please?

**Comment by tomkerkhove** [comment]
Are you part of that team?

**Comment by amirschw** [comment]
I am! Currently using @SagiVaknin's branch to export NAT Gateway metrics. I wanted to add an alert for SNAT Port Exhaustion based on [this doc](https://learn.microsoft.com/en-us/azure/virtual-network/nat-gateway/nat-metrics#alerts-for-snat-port-exhaustion) and noticed that the ConnectionState dimension isn't sent to the StatsD sink.

**Comment by amirschw** [comment]
My team ended up switching to the Prometheus sink since we have solid integration with kube-prometheus-stack. But I guess it's still an issue for Sagi and the rest of the org that use statsd.
