### ISSUE TITLE
Add Traffic Manager resource discovery

### ISSUE THREAD

**Issue by jstaffans-relex** [tomkerkhove/promitor#2192]
### Proposal

It does not seem to be possible to monitor Traffic Manager because resource discovery does not support it: https://learn.microsoft.com/en-us/azure/traffic-manager/

Would it be possible to add this? What would be the steps if one would want to contribute this?

### Component

Resource Discovery

**Comment by tomkerkhove** [comment]
I'd love to review a contribution for this indeed, thank you!

This commit shows how you can add scraper + support resource discovery, I hope this is helpful?
https://github.com/tomkerkhove/promitor/commit/d2976476df71d9052e4510e82c32f203a3ffb95f

Here is some general guidance: https://github.com/tomkerkhove/promitor/blob/master/CONTRIBUTING.md
