### ISSUE TITLE
ClientID should be optional when using UserAssignedManagedIdentity

### ISSUE THREAD

**Issue by amirschw** [tomkerkhove/promitor#2237]
### Proposal

When using UserAssignedManagedIdentity for auth, the ClientID of the Managed Identity (aka `identityId`) is currently required:
https://github.com/tomkerkhove/promitor/blob/7e7a66fb706509d58509916a9b0a6ce1a8214c48/src/Promitor.Integrations.Azure/Authentication/AzureAuthenticationFactory.cs#L70-L76

This becomes an issue at scale, because it requires some work to get the ClientID from the resource and put it in the configuration when deploying Promitor. Therefore, since `ManagedIdentityCredential` doesn't require ClientID (it's only required by IMDS if the VM has multiple user-assigned managed identities, but can be added by NMI when using aad-pod-identity), I suggest making it optional.

Alternatively, ResourceID should be supported in addition to ClientID (it is supported by IMDS and [ManagedIdentityCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential.-ctor?view=azure-dotnet#azure-identity-managedidentitycredential-ctor(azure-core-resourceidentifier-azure-identity-tokencredentialoptions))). ResourceID is easier to pass in configuration since its value is known even prior to the creation of the resource (`/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity_name>`).

Related to #2218

### Component

Resource Discovery, Scraper

### Contact Details

Amir.Schwartz@microsoft.com

**Comment by ravidbro** [comment]
+1

**Comment by tomkerkhove** [comment]
Hm, it's been a while since I looked at user-defined managed identities but aren't these required?

**Comment by amirschw** [comment]
It is not required, it is only an issue when there's more than one user-assigned managed identity attached to the VM. And even in this case, when aad-pod-identity is used, NMI will add the client id to the request before passing it on to IMDS.

**Comment by tomkerkhove** [comment]
THank you for the contribution!
