### ISSUE TITLE
Where do I get the appkey from?

### ISSUE THREAD

**Issue by nikolay** [tomkerkhove/promitor#249]
I am new to Azure and it's super complicated compared to AWS and others. In your documentation, you talk about "AD entity". Can you clarify what *exactly* you mean by that?

**Comment by tomkerkhove** [comment]
You need to create an Azure AD Application which will be used to authenticate against Azure.

You can find a guide [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal).

**Comment by nikolay** [comment]
Thank you, @tomkerkhove!
