### ISSUE TITLE
Promitor CI Broken for Scraper and Resource Discovery Agents

### ISSUE THREAD

**Issue by hkfgo** [tomkerkhove/promitor#2553]
### Report

I'm sure people may already be aware of some of these issues. Unfortunately I don't think the failures are transient. Some scraper agent e-2-e tests failing because OTEL Collector sink does not give any metrics. Resource discovery agent e-2-e tests are failing because they consistently discover more resources than expected. 

This blocks merging of both feature PRs and security updates. I am taking a look at the moment but don't have a clear idea on why yet. I would greatly appreciate any help! 

### Expected Behavior

Scraper and resource discovery agent e-2-e tests should continue to pass since no change was done to their underlying logic. 

### Actual Behavior

Some e-2-e tests are failing as described

### Steps to Reproduce the Problem

Take a at any of the recent PRs :( 

### Component

Resource Discovery, Scraper

### Version

Scraper-v2.11.2

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

### Logs

```shell
example
```

### Platform

Microsoft Azure

**Comment by tomkerkhove** [comment]
Is this not a local runtime issue rather than a CI issue?

**Comment by hkfgo** [comment]
This is also fixed with https://github.com/tomkerkhove/promitor/pull/2552 and https://github.com/tomkerkhove/promitor/pull/2567
