### ISSUE TITLE
OpenTelemetry Collector Sink Broken 

### ISSUE THREAD

**Issue by hkfgo** [tomkerkhove/promitor#2571]
### Report

<img width="1450" alt="Screenshot 2024-11-01 at 2 56 36 PM" src="https://github.com/user-attachments/assets/2dde2d57-1637-4a7d-be26-6b59e192159e">
The first export cycle is successful, but not subsequent ones. And it's an insidious failure that tricks CI to pass :/ We'd released many Promitor versions with this bug. The latest working version is 2.8.0. 

### Expected Behavior

Continuous stream of metrics exported 

### Actual Behavior

Only the first export is successful then nothing 

### Steps to Reproduce the Problem

Configure an OpenTelemetry sink like documentation describes. There will either be no metrics at all or a few data points followed by nothing. 

### Component

Scraper

### Version

Scraper-v2.11.2

### Configuration

Configuration:

```yaml
# Add your scraping configuration here
```

### Logs

```shell
example
```

### Platform

Microsoft Azure

**Comment by hkfgo** [comment]
Here's more of a proof and some good news. I reverted https://github.com/tomkerkhove/promitor/pull/2239 in my test branch https://github.com/tomkerkhove/promitor/pull/2567/files, where the [OpenTelemetryCollectorMetricSink.cs](https://github.com/tomkerkhove/promitor/pull/2567/files#diff-3860310bca8263df9a9f5b43bd3f06fdac0975d7d85467b086550aa561883316) is reverted to the earliest version. 

I was able to get OpenTelemetry tests to pass every time(I tried 3 times total). Feel free to have a look yourself. It's a little confusing because the scraper CI is marked red but only because logs printed to `stderr`. The tests themselves all passed.

**Comment by hkfgo** [comment]
I think it's safe to say that using channels in that commit broke the sink. Do you mind explaining what concurrency issue you were trying to fix? 

Although tests pass with the revert, I did observe that the metrics reported are still missing labels. I can try incorporating changes from this past commit https://github.com/tomkerkhove/promitor/pull/2183/files#diff-3860310bca8263df9a9f5b43bd3f06fdac0975d7d85467b086550aa561883316 and see if a fully working version can be produced.

**Comment by tomkerkhove** [comment]
That's very nice finding - Thank you!

I think the issue has the details on what was going on but it was not fully thread-safe. Let's see if we can get the labels working and then we can revert that PR and move forward.

**Comment by hkfgo** [comment]
Sounds good. Let's move forward without using channels, the circle back on that concurrency issue?

**Comment by hkfgo** [comment]
I incorporated label processing logic into the above PR. The code passed CI and is running smoothly in our staging env. I'll clean up the PR a bit and it should be in good shape to merge

**Comment by tomkerkhove** [comment]
Thanks a ton, highly appreciated!

As ref: https://github.com/tomkerkhove/promitor/pull/2567

**Comment by tomkerkhove** [comment]
Fixed in https://github.com/tomkerkhove/promitor/pull/2567, thank you very much @hkfgo!

**Comment by tomkerkhove** [comment]
Sure, would you mind opening a PR to update the Helm chart and package things please? I can do it but not this week; sorry

**Comment by hkfgo** [comment]
I filed an issue here for a better place to talk about it: https://github.com/promitor/charts/issues/174
