### ISSUE TITLE
Provide more unit tests for configuration deserialization

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#283]
For our configuration deserialization we have implemented our own deserialization due to our metric configuration that can have different types. 

This is very fragile and only has one test. We should add more and cover all scenarios.

**Comment by adamconnelly** [comment]
Hey Tom - I think you could probably close this issue now since I added a load of unit tests for the configuration deserialization as part of #513

**Comment by tomkerkhove** [comment]
That's right, thanks!
