### ISSUE TITLE
Provide capability to opt-out of metric timestamps

### ISSUE THREAD

**Issue by datadot** [tomkerkhove/promitor#290]
Including timestamp should be a configurable parameter.

Forcing timestamps within a cloud environment causes issues as hosts are rarely fully in time, adding timestamp to all scrape outputs causes issues when ingesting by Prometheus:

Error on ingesting samples that are too old or are too far into the future

**Comment by datadot** [comment]
This is related to PR https://github.com/tomkerkhove/promitor/pull/285

**Comment by tomkerkhove** [comment]
What is your concern by always adding timestamps for the values that we report?

**Comment by datadot** [comment]
Within say an AKS cluster nodes are unlikely to hold accurate time, so when you scrape metrics you get a constant error causing metrics to be ignored.

The error the scrape reports is:

Error on ingesting samples that are too old or are too far into the future.

Can’t find a way to ignore the timestamp and as such metrics never get imported. The timestamps are also not always necessary so seems a bit over the top forcing on everything?

**Comment by tomkerkhove** [comment]
They are there to report when we've last checked but will provide a way to opt-out. Is that good enough for you?

**Comment by tomkerkhove** [comment]
This is now available in 0.6.0
