### ISSUE TITLE
fetch all avaliable resources

### ISSUE THREAD

**Issue by pad92** [tomkerkhove/promitor#305]
I don't have the impression that Promitor can collect all the metric azure monitors as it stands.

#### Specification

- [ ] Request # 1
if no metric specifed, fetch all from https://management.azure.com/subscriptions/{subscriptionId}/resources?
- [ ] issue #114 : Duplicate with this one ?

**Comment by tomkerkhove** [comment]
This is not supported now and will most probably not be supported. This approach is too greedy and will cause Promitor to be throttled.

I would recommend to configure the resources that you need as this also is a clear expectation what to expect for your consumers.

**Comment by pad92** [comment]
ok thx
