### ISSUE TITLE
Provide support for scraping metrics for Azure Database for MySQL

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#324]
Provide support for scraping metrics for Azure Database for MySQL

**Comment by marcoboffi** [comment]
Please plan also "Resource discovery" feature. Azure mysql is widely used from Azure customers.

**Comment by tomkerkhove** [comment]
All new Scrapers will come with resource discovery unless Azure Resource Graph does not support it.

But I'll look into it!
