### ISSUE TITLE
Provide support for scraping metrics for Azure Kubernetes Service

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#333]
Provide support for scraping metrics for Azure Kubernetes Service

**Comment by tomkerkhove** [comment]
If you are already using Prometheus you'll have all the info there already

**Comment by jkataja** [comment]
I've the initial implementation, however need to test and clear the contributor agreement first.

**Comment by tomkerkhove** [comment]
Awesome, thank you!
