### ISSUE TITLE
Provide support for scraping metrics for Azure Cache for Redis

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#335]
Provide support for scraping metrics for Azure Cache for Redis

**Comment by jcorioland** [comment]
Hi @tomkerkhove - I am currently looking at this one - will update you here :)

**Comment by tomkerkhove** [comment]
Hi Julien, do you mean you want to contribute this scraper? If so, thanks!

**Comment by jcorioland** [comment]
Hey Tom, yes sorry, looking to contribute on this scraper!

**Comment by tomkerkhove** [comment]
Awesome, thank you!
