### ISSUE TITLE
Provide support for scraping metrics for Azure IoT Hubs

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#372]
Provide support for scraping metrics for Azure IoT Hubs

**Comment by ChristianEder** [comment]
I am completely new to Promitor and prometheus, but I will give this a try - because I really need it myself :-)

**Comment by tomkerkhove** [comment]
Great to hear @ChristianEder, this guide should be able to help you - https://github.com/tomkerkhove/promitor/blob/master/adding-a-new-scraper.md

If you are new customer, feel free to [get listed](https://forms.gle/xrWpP8iAni7PknAx8) or ping me offline if you have questions around Promitor or contribution itself.
