### ISSUE TITLE
Provide support for scraping account-level metrics for Azure Storage Files

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#386]
Provide support for scraping account-level metrics for Azure Storage Files based on this approach: https://docs.microsoft.com/en-us/azure/storage/common/storage-metrics-in-azure-monitor#resource-id-for-the-storage-services

**Comment by helayoty** [comment]
👍

**Comment by tomkerkhove** [comment]
Metrics for one specific resource will be handled via #446 and focus on account-level metrics for all file resources.
