### ISSUE TITLE
Provide capability to configure custom metric provider over REST

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#388]
Provide capability to configure custom metric provider over REST.

This would enable consumers to read metrics from a sidecar and expose it in the same scraping endpoint.

**Comment by tomkerkhove** [comment]
Thinking about this again I'm not sure if this actually makes sense.

I suggest to close this one, what do you think @brusMX @jsturtevant?

**Comment by brusMX** [comment]
Not supported yet. You can close it

**Comment by tomkerkhove** [comment]
@brusMX This is not related to Azure Monitor but rather capability to provide your own metrics.

However, I'm still closing this as it's not something we should provide.
