### ISSUE TITLE
Provide support for scraping metrics for Azure Storage Queue

### ISSUE THREAD

**Issue by michaelkruglos** [tomkerkhove/promitor#399]
Provide support for scraping metrics for Azure Storage Queue.

**Comment by tomkerkhove** [comment]
Thanks for your feature request, we are adding this as part of #64

**Comment by michaelkruglos** [comment]
#64 is about Azure Monitor, but I don't think Azure Monitor supports queue sizes from what I understand. Are you sure it's not relevant?

**Comment by tomkerkhove** [comment]
The goal is to display metrics for Azure Storage Queue depth, if we can't get it from Azure Monitor we'll make sure that we use another data source.

Is that ok for you? Will clarify this in #64 if you agree!

**Comment by michaelkruglos** [comment]
Thanks. I'd like to work on it. I hope to submit a PR soon if you don't mind.

**Comment by tomkerkhove** [comment]
Sounds good, thanks!
