### ISSUE TITLE
Release new docker image

### ISSUE THREAD

**Issue by michaelkruglos** [tomkerkhove/promitor#433]
Please, release new docker image with latest updates

### Specification

- [ ] Release new docker image

**Comment by tomkerkhove** [comment]
v1.0 is not ready yet and can be tracked here - https://github.com/tomkerkhove/promitor/milestone/7. This is coming in April, you can use CI Docker image based on your PR, might release a preview build later this week as well.

Closing given the above

**Comment by tomkerkhove** [comment]
You can use our preview - https://github.com/tomkerkhove/promitor/releases/tag/1.0.0-preview-1
