### ISSUE TITLE
Provide user guide to deploy, run & scrape Promitor from Prometheus

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#440]
Provide user guide in documentation on how to:
1. Configure Promitor
2. Deploy Promitor
3. Configure Prometheus to scrape from Promitor

**Comment by tomkerkhove** [comment]
This will be picked up by @immuzz

**Comment by tomkerkhove** [comment]
@immuzz Did you manage to make any progress on this or do you prefer to hand this over to somebody else?

**Comment by immuzz** [comment]
I have been working on the walkthrough with @lee0c . I 'll be doing a PR this week.

**Comment by tomkerkhove** [comment]
Awesome, thank you!

**Comment by tomkerkhove** [comment]
How are things going on this front @immuzz ?

**Comment by tomkerkhove** [comment]
How are things going on this front @immuzz ?
