### ISSUE TITLE
Standarize Markdownlinter

### ISSUE THREAD

**Issue by brusMX** [tomkerkhove/promitor#453]
It would be desirable to lint markdown for the documentation and have it in a standard format.

### Specification

- Update all files to be lint to markdown
- Implement the [markdown lint cli](https://github.com/igorshubovych/markdownlint-cli) in the devops pipeline

**Comment by adamconnelly** [comment]
I've created a PR that adds markdownlint to the project, runs it in Azure Pipelines, and fixes all the issues in the existing files.

I think we could go a bit further and use Husky to help prevent code that fails linting from being committed, but I want to wait to see what Tom thinks before doing that.
