### ISSUE TITLE
Support multiple resource groups in helm deployment

### ISSUE THREAD

**Issue by lee0c** [tomkerkhove/promitor#459]
Follow up to #17, #294 

### Specification

Add resource group override for individual metrics to helm values/config map.

**Comment by lee0c** [comment]
Looking over @brusMX 's multi RG support, the current chart should actually support this by default. Will be fixed w/ https://github.com/tomkerkhove/promitor/pull/457

**Comment by tomkerkhove** [comment]
@lee0c 	Based on your comment I think we can close this, right?

**Comment by lee0c** [comment]
Yes, the helm chart provides this support

**Comment by tomkerkhove** [comment]
🎉
