### ISSUE TITLE
Add docs for debug/troubleshooting

### ISSUE THREAD

**Issue by brandonh-msft** [tomkerkhove/promitor#471]
As contributors write new code for Promitor, it will become imperative we have debug/troubleshooting steps to help them along the way.

We should include this as part of our docs, perhaps in a 'Contributing' area?

cc @brusMX

**Comment by tomkerkhove** [comment]
That's a good suggestion @brandonh-msft 	, would it make sense to add it [here](https://github.com/tomkerkhove/promitor/blob/master/.github/CONTRIBUTING.md)? Maybe a dedicated section/file would be better instead which has a pointer in https://github.com/tomkerkhove/promitor/blob/master/.github/CONTRIBUTING.md?
