### ISSUE TITLE
Reintroduce fallback for scraping schedule?

### ISSUE THREAD

**Issue by brandonh-msft** [tomkerkhove/promitor#477]
Prior to the fix for #259 (merged by PR #473), it was possible to _not_ specify a scraping interval - default or otherwise - for Promitor. However, the PR introduced a change where - at minimum - `metricDefaults.scraping.schedule` was required in the `metrics-declaration.yaml` file. This is a change from previous where the `PROMITOR_SCRAPING_SCHEDULE` environment variable was optional and would fall back to a 5 minute schedule if not specified.

I'm opening this "bug" issue to discuss this change; if it is indeed a bug we can introduce the fallback.

Worth noting that this breaking change necessitated a change to the helm chart (#476)

cc @tomkerkhove for his input

**Comment by tomkerkhove** [comment]
Thanks for the follow-up on it @brandonh-msft.

Personally, I would suggest to keep it as is because it's more explicit in the scraping schedule rather than the optional approach.

What do you think?

**Comment by brandonh-msft** [comment]
I'm inclined to agree; was just a breaking change @lee0c encountered while doing the helm work. wanted to make sure it was addressed

**Comment by tomkerkhove** [comment]
No problem, thanks for doing that and happy we have an agreement!
