### ISSUE TITLE
License on promitor.io is granted by Codit, instead of Tom Kerkhove, which is wrong

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#480]
The license on promitor.io is granted by Codit, instead of Tom Kerkhove, as original creator which is not correct nor in line with [the official license on GitHub](https://github.com/tomkerkhove/promitor/blob/master/LICENSE)

This should be fixed by updating the docs.

![image](https://user-images.githubusercontent.com/4345663/55380643-18363c00-5521-11e9-8dcd-049838985905.png)

**Comment by tomkerkhove** [comment]
Can you please confirm this is the case @samvanhoutte?

**Comment by SamVanhoutte** [comment]
Hello Tom,
Yes, I agree.  I assume that was a copy/past on your side?
Best regards

**Comment by tomkerkhove** [comment]
That's right, my bad!
