### ISSUE TITLE
Provide docs on how to build & test the codebase

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#484]
Provide docs on how to build the codebase so that people can get started.

Should include how to :
- Build our solution
- Run unit tests
- Build Docker image

Location is still TBD - Either README or [CONTRIBUTING](https://github.com/tomkerkhove/promitor/blob/master/.github/CONTRIBUTING.md)

**Comment by adamconnelly** [comment]
I don't mind picking this up, but any chance you can quickly explain to me how you go about running Promitor locally for testing?

The reason I ask is that I couldn't get Promitor to work locally without editing some of the code because it was looking in a hard-coded location for the config files, so I'm guessing I wasn't running it in the way you intended.

Also, at the moment I've only got VS 2017 installed, which means the Docker project doesn't work for me. I'm assuming you must be using VS 2019. Is that correct?

**Comment by tomkerkhove** [comment]
In theory all you have to change is the the Azure AD app to authenticate with (https://github.com/tomkerkhove/promitor/blob/master/src/docker-compose.override.yml#L7) and update the local metric config (https://github.com/tomkerkhove/promitor/blob/master/src/metric-config.yaml) to work with your subscription or scrape the resources you want - That should be it for the rest.

In terms of testing, it's still manual for now where I verify that the metrics are outputted and make sense, but at some point we'll have integration tests (#33) but it's all about prios and time.

I am using 2019 indeed but used 2017 for Promitor before that which worked fine, did you read the docs on this?

https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/visual-studio-tools-for-docker

I would certainly get it if you couldn't send a PR for this and that's ok. If you would get it working and are up for it, I would be more than happy - But don't feel obliged to do it!

**Comment by adamconnelly** [comment]
Ok - I've sent a PR. It needs to at least be tweaked a bit, but I figured it gave us a starting point to talk about.

Also, I've tried running the Docker project again, but I just seem to get the following error:

```shell
6>docker ps --filter "status=running" --filter "name=promitordocker8059240556648310614_promitor.scraper_" --format {{.ID}} -n 1
6>db560a1fd95b
6>docker exec -i db560a1fd95b /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
6>OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(310,5): error : .
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(310,5): error : 
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(310,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
6>Done building project "Promitor.Docker.dcproj" -- FAILED.
```

It might be something to do with the way I've configured my machine. I can also try VS 2019 at some point to check whether that works.
