### ISSUE TITLE
"No default aggregation" warning is printed when one is provided

### ISSUE THREAD

**Issue by ResDiaryLewis** [tomkerkhove/promitor#521]
[This line of code](https://github.com/tomkerkhove/promitor/blob/2c72d10642c02051996632c891ff1cab7c384e2c/src/Promitor.Core.Scraping/Configuration/Serialization/Core/AggregationDeserializer.cs#L23) prints a warning `No default aggregation was configured` when a default aggregation _is_ configured.

## Expected Behavior
The warning should be printed when the default aggregation is _not_ configured.

## Actual Behavior
The warning is printed when the default aggregation is configured.

## Steps to Reproduce the Problem

  1. Provide a default aggregation in `metricDefaults.aggregation.interval`
  2. Start Promitor
  3. View the logs

## Specifications

  - Version: `1.0.0-preview-3`
  - Platform: Kubernetes
  - Subsystem: Docker

**Comment by tomkerkhove** [comment]
Well spotted, thank you!

**Comment by tomkerkhove** [comment]
This is now available in `1.0.0-preview-4` - https://github.com/tomkerkhove/promitor/releases/tag/1.0.0-preview-4

Thanks for reporting this @ResDiaryLewis!

**Comment by ResDiaryLewis** [comment]
That's great, cheers for the fast fix 👍
