### ISSUE TITLE
Service Bus Queues should be able to scrape all queues in namespace, not just one

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#529]
Service Bus Queues should be able to scrape all queues in namespace, not just one.

It should annotate all queues that it scraped with a `entity_name` label in Prometheus endpoint.

Relates to #513 and was suggested in [this comment](https://github.com/tomkerkhove/promitor/issues/513#issuecomment-487489653) by @marcinbudny
### Checklist

- [ ] Make `queueName` optional in the configuration
- [ ] Scrape all queues if no queue name was configured
- [ ] Always apply `entity_name` label, even if `queueName` was configured for consistency reasons

**Comment by tomkerkhove** [comment]
One thing we'll need to evaluate is if we can get it out of the box or if this means increasing required permissions for our Azure AD app.

If that is the case we'll need to see if it's worth it.

**Comment by ChristianEder** [comment]
I am currently struggling with a similar issue, but I'm not sure if it is totally the same: I cannot get service bus queue metrics for more than 1 queue. I tried 2 things:

1) Using a ServiceBusQueue scraper with multiple resources:

```json
- name: azure_service_bus_active_messages
  description: "Count of active messages per queue / topic"
  resourceType: ServiceBusQueue
  azureMetricConfiguration:
    metricName: ActiveMessages
    aggregation:
      type: Average
  resources:
  - namespace: my-namespace
    queueName: queue1
  - namespace:  my-namespace
    queueName: queue2
  - namespace:  my-namespace
    queueName: queue3```

2) Using a Generic scraper with multiple resources, using filters:
```json
- name: azure_service_bus_deadlettered_messages
  description: "Count of dead-lettered messages per queue / topic"
  resourceType: Generic
  azureMetricConfiguration:
    metricName: DeadletteredMessages
    aggregation:
      type: Average
  resources:
  - resourceUri: Microsoft.ServiceBus/namespaces/my-namespace
    filter: EntityName eq 'queue1'
  - resourceUri: Microsoft.ServiceBus/namespaces/my-namespace
    filter: EntityName eq 'queue2'
  - resourceUri: Microsoft.ServiceBus/namespaces/my-namespace
    filter: EntityName eq 'queue3'```

The 1) approach leads to only the metrics for `queue3` being reported, the 2) approach to only the unfiltered, total sum of `DeadletteredMessages` being reported. Is this a known issue or am I doing something wrong here?

**Comment by tomkerkhove** [comment]
Hm that feels like a bug, would you mind creating a new issue for this please? Sorry for this 😐

**Comment by ChristianEder** [comment]
Done: #1050
