### ISSUE TITLE
How should we report missing metrics

### ISSUE THREAD

**Issue by datadot** [tomkerkhove/promitor#546]
If you have a time series (example blob storage exporting metric transactions) you will receive a set of results as follows:

`"timeseries": [
                {
                    "metadatavalues": [],
                    "data": [
                        {
                            "timeStamp": "2019-05-09T15:34:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:35:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:36:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:37:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:38:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:39:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:40:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:41:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:42:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:43:00Z",
                            "total": 37
                        },
                        {
                            "timeStamp": "2019-05-09T15:44:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:45:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:46:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:47:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:48:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:49:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:50:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:51:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:52:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:53:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:54:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:55:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:56:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:57:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:58:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T15:59:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:00:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:01:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:02:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:03:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:04:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:05:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:06:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:07:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:08:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:09:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:10:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:11:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:12:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:13:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:14:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:15:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:16:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:17:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:18:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:19:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:20:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:21:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:22:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:23:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:24:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:25:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:26:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:27:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:28:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:29:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:30:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:31:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:32:00Z"
                        },
                        {
                            "timeStamp": "2019-05-09T16:33:00Z"
                        }
                    ]
                }
            ]`

However when promitor queries this it returns -1 for any query that doesn't return a value.

I believe it makes more sense to return 0 in this case as advised by prometheus "Avoid missing metrics" [https://prometheus.io/docs/practices/instrumentation/#counter-vs-gauge-summary-vs-histogram](https://prometheus.io/docs/practices/instrumentation/#counter-vs-gauge-summary-vs-histogram)

**Comment by tomkerkhove** [comment]
Thanks for reporting, this is indeed on purpose to clarify that a metric could not be found.

In this case 0 makes sense, but what if you're measuring queues? In that case 0 is a legit value and can cause bad assumptions.

**Comment by datadot** [comment]
I concur that 0 may not be valid in all scenarios.

The advice from the Prometheus documentation is that in the scenario that a 0 doesn't make sense (or is misleading) a NaN should be returned.  I wouldn't suggest that Promitor should make this decision, I believe a metric configuration along the lines of missingMetric should be added where admins can elect to make it 0 or NaN or leave the current value of -1 at the individual metric level (not global).

**Comment by tomkerkhove** [comment]
I'll leave it open for a while so people can chime in and provide their feedback, is that ok @datadot?

**Comment by tomkerkhove** [comment]
Checking if we can get NaN support - https://github.com/PrometheusClientNet/Prometheus.Client/issues/65

**Comment by tomkerkhove** [comment]
### Tasklist
- [ ] Make it configurable hat value to use in case of no metric value (`NaN`, `0`, `-1`, etc)
- [ ] Surface configuration in Helm chart
- [ ] Provide documentation on configuration incl the why

**Comment by brusMX** [comment]
Adding on this item, our customer is concerned that if you get a `-1` you have no clear way to understand what happened.
Sounds like putting a Log in place explaining it could help out, but we don't want to spam with too many logs. 
The use case right now is that you could probably have  a bad `metrics.config` file with invalid intervals for a specific metric and there is no clear understanding on what happened there. Not sure if i should open another issue for this though.

**Comment by tomkerkhove** [comment]
I think in your case `NaN` would make sense @brusMX.

Your bad configuration scenario will be blocked in the future (#465). As of today, we will use the closest aggregation period that is available. If we need to deviate from what is configured we already trace a warning - https://github.com/tomkerkhove/promitor/blob/master/src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs#L96

**Comment by tomkerkhove** [comment]
@datadot How much of an issue would it be if the metric type switched from `gauge` to `untyped`?

**Comment by tomkerkhove** [comment]
Documentation is up here: https://promitor.io/configuration/v1.x/runtime#scraping-prometheus

**Comment by tomkerkhove** [comment]
The nice folks of PrometheusClientNet have implemented our change request and we'll still be able to use `gauge` metric. They are planning to ship 3.1 in the near future

See https://github.com/PrometheusClientNet/Prometheus.Client/issues/65

**Comment by tomkerkhove** [comment]
Done via https://github.com/tomkerkhove/promitor/pull/698
