### ISSUE TITLE
Add "Setting up a Prometheus alert" to AKS deployment walkthrough

### ISSUE THREAD

**Issue by lee0c** [tomkerkhove/promitor#566]
Add a section to the Promitor on AKS w/ Prometheus & Grafana walkthrough detailing how to set up an alert based on the metric being monitored (Service Bus Queue length).

This needs to use the in-cluster deployment of Prometheus, and will likely involve setting up an alert via the Prometheus helm chart.

**Comment by tomkerkhove** [comment]
I think this goes beyond the scope of the project, closing for now.
