### ISSUE TITLE
Provide runtime configuration override via environment variables

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#594]
In #431 we've introduced our runtime YAML configuration, however, in certain scenarios, it's good to be able to override them via environment variables as suggested by @jdevalk2 in [his comment](https://github.com/tomkerkhove/promitor/issues/431#issuecomment-500465862).

I like the suggestion of using a similar approach to Grafana :

> [server]
> name=bla
> 
> Can be overridden with environment variable GF_SERVER_NAME=bla2

**Comment by tomkerkhove** [comment]
@jdevalk2 Since our configuration is now a YAML file, but able to be overriden via ENV variables, can we close this one?

https://promitor.io/configuration/v1.x/runtime#overriding-configuration-with-environment-variables

**Comment by jdevalk2** [comment]
Its exactly what this ticket talks about so this one can be closed. LGTM.
