### ISSUE TITLE
Move CI Docker image to GitHub Package Registry

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#648]
Move CI Docker image to GitHub Package Registry instead of Docker Hub to create a clear boundary between both image types.

Guidance on publishing Docker image to GitHub Package Registry:
https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry

Moving will have an impact on our PR bot and CI Helm chart.

**Comment by tomkerkhove** [comment]
Looks like GitHub Package Registry automatically creates a new GitHub release per image push, which we don't want.

Post-poning for now.

**Comment by adamconnelly** [comment]
@tomkerkhove on a related note - it looks like you manually decide when to create a release at the moment. I'm just thinking it would be really useful to create a new pre-release image for every merge into master. That would make it easier to try out pre-release versions without having to build our own image.

**Comment by tomkerkhove** [comment]
Well in theory you already have those via the PR. The reason they are not there yet is that I want to keep the releases clean with what is actually ready.

For example, some PRs are part of a bigger whole and will not give a workable image.

However, I'm always open so feel free to create a dedicated issue for that and we'll see what the demand is!

**Comment by tomkerkhove** [comment]
Unless you mean a new tag without release on the repo when you say `pre-release`? Then that is possible.

**Comment by adamconnelly** [comment]
If I can use the PR images that's fine for me. Are they available indefinitely, or do they have a time limit?

But yeah, a new tag without a release on the repo would be totally fine. Just some way to get the most recent build easily.

**Comment by tomkerkhove** [comment]
They are available indefinitely for now but you are right they are 1) not discoverable 2) one tag would be better.

Tracking in #693, feel free to jump over and provide input

**Comment by tomkerkhove** [comment]
When changing this we should update our CI bot to work with https://developer.github.com/v3/activity/events/types/#registrypackageevent

**Comment by tomkerkhove** [comment]
Images are already being pushed.

Remaining work:
- [ ] Verify if we can enable anonymous access
- [ ] Change our current Docker Hub agent
- [ ] Stop pushing to Docker Hub
