### ISSUE TITLE
Provide support for Windows containers

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#67]
Provide support for Windows containers.

- [x] Provide support for Windows containers
- [x] Build Windows & Linux container in CI
- [x] Build Windows & Linux container in release
- [x] Document supported containers
- [x] Update tagging strategy

_Should be fairly easy via multi-arch containers_

**Comment by dhavalshah02** [comment]
Any update on this?

**Comment by tomkerkhove** [comment]
It's not planned yet but feel free to cover your scenario and will consider it!
