### ISSUE TITLE
Documentation linter should not validate the Changelog template

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#775]
Documentation linter should not validate the Hugo Changelog template which is blocking all PRs, for [example](https://tomkerkhove.visualstudio.com/Promitor/_build/results?buildId=1605&view=logs&jobId=b637e6d4-8c25-5a70-7224-033d1971c20d&j=b637e6d4-8c25-5a70-7224-033d1971c20d&t=036717fa-c21c-55a1-e0cf-05e6088c644a).

The CLI should ignore the template in `changelog/themes`.

**Comment by tomkerkhove** [comment]
Are you up for this @adamconnelly ?

**Comment by adamconnelly** [comment]
@tomkerkhove I'm happy to - I'm just pretty busy at work right now so I can't make a guarantee about how quickly I'll be able to take a look. I think it's just a case of adding an extra parameter to the command that runs to tell it to ignore a folder, so in theory it should be fairly simple to fix.

**Comment by tomkerkhove** [comment]
I've had a look but couldn't find it so would be good to have you jump in if possible!

It's mitigated for now so no rush and take your time, make sure you relax as well!
