### ISSUE TITLE
Powerstate / InstanceView Possible?

### ISSUE THREAD

**Issue by vexter0944** [tomkerkhove/promitor#792]
### Specification

- Is there a way to monitor powerstate with promitor?  Either here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.fluent.powerstate?view=azure-dotnet possibly using generic resource or via api like this: https://management.azure.com/subscriptions/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/RG_NAME_HERE/providers/Microsoft.Compute/virtualMachines/VM_NAME_HERE/InstanceView?api-version=2019-03-01

**Comment by tomkerkhove** [comment]
Promitor is purely metric based but it looks like Powerstate is more of an enumeration or not?

If it's exposed via an Azure Montior metric it should be possible, but otherwise it will not be supported - Sorry!

**Comment by vexter0944** [comment]
I don't believe it is exposed via the Azure Monitor metric.  Thanks for getting back to me so quickly, much appreciated!

**Comment by tomkerkhove** [comment]
My pleasure!
