### ISSUE TITLE
Provide support for Azure Managed Identities

### ISSUE THREAD

**Issue by ricardoalcazar** [tomkerkhove/promitor#804]
From a security perspective, it is more secure to authenticate to the Azure subscription via Managed Identity rather than passing client ID and client secret via parameter. There is an alternative way of passing secure credentials via Docker secrets, but our enterprise requires that credentials are managed via Active Directory or KeyVault. 

Is there a roadmap to implement Managed Identities as a feature in the near future?

**Comment by tomkerkhove** [comment]
We hear you for sure! We're tracking this via
#444.

OK for you if we close this one as it's a duplicate?

**Comment by ricardoalcazar** [comment]
Yes, please feel free to close, I appreciate the quick response!

**Comment by tomkerkhove** [comment]
Always happy to help!
