### ISSUE TITLE
Addition of scrappers for: Network/ExpressRouteCircuits and Network/ApplicationGateways

### ISSUE THREAD

**Issue by hajdukd** [tomkerkhove/promitor#855]
### Specification

This is more or less an open question about how much work is required to add additional ResourceTypes scrappers. I can see the currently supported ones are here:
https://github.com/tomkerkhove/promitor/tree/master/src/Promitor.Core.Scraping/ResourceTypes

And I need metrics from those resources:

Network/ExpressRouteCircuits and Network/ApplicationGateways

### API Specification
N/A

**Comment by hajdukd** [comment]
Additionally:

Wouldnt it make more sense to make resourcegroup metric config dependant ?

Maybe I understood the charts config wrong but I would like to read metrics of services in one resourcegroup together with metrics of services in another resourcegroup.

**Comment by tomkerkhove** [comment]
Application Gateway is planned via https://github.com/tomkerkhove/promitor/issues/313 but I'm not sure what the other Azure services are that you are interested in, would you mind elaborating on them please?

All our supported services are documented on https://promitor.io/configuration/v1.x/metrics/#supported-azure-services, but we also provide a generic scraper which is more advanced but allows you to work with other services that are not supported yet: https://promitor.io/configuration/v1.x/metrics/generic-azure-resource

So you can basically scrape every metrics that is supported already: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported

If you want to contribute one, feel free to look for one in the issues and give me a heads up or propose one which we can discuss.

In terms of implementation, everything is defined in https://github.com/tomkerkhove/promitor/blob/master/adding-a-new-scraper.md which should guide you through the process. But as said, feel free to go to the issue first

> Maybe I understood the charts config wrong but I would like to read metrics of services in one resourcegroup together with metrics of services in another resourcegroup.

It's fully up to you. By default a resource group is defined but it can be overriden for every metric, so if you want to scrape multiple resource groups it's also supported.

https://promitor.io/configuration/v1.x/metrics/#azure

Hope this answers your question. Feel free to ask more questions.

**Comment by hajdukd** [comment]
Thanks for the explanations

**Comment by tomkerkhove** [comment]
My pleasure and feel free to vote on missing scrapers or request new ones
