### ISSUE TITLE
Support Prometheus Operator in Helm chart

### ISSUE THREAD

**Issue by DaveOHenry** [tomkerkhove/promitor#885]
The chart should (optionally) create a ServiceMonitor object so it can seamlessly be integrated into a Prometheus Operator deployment.

Some examples can be found here:
- https://github.com/helm/charts/blob/master/stable/prometheus-postgres-exporter/templates/servicemonitor.yaml
- https://github.com/helm/charts/blob/master/stable/prometheus-redis-exporter/templates/servicemonitor.yaml
- https://github.com/helm/charts/blob/master/stable/prometheus-rabbitmq-exporter/templates/servicemonitor.yaml

**Comment by tomkerkhove** [comment]
Good suggestion, adding it to the backlog but always open for a PR.

**Comment by tomkerkhove** [comment]
Awesome, thank you!

**Comment by tomkerkhove** [comment]
Closing in favor of https://github.com/promitor/charts/issues/7.

In case you want to still contribute this @DaveOHenry, https://github.com/promitor/charts is the place to be!
