### ISSUE TITLE
Binary Executable for Linux

### ISSUE THREAD

**Issue by muralikanagala** [tomkerkhove/promitor#900]
Many people are still running Prometheus and Exporters on Linux machines as services. Running a Docker container becomes a special case in environments where there is no Docker in place yet. 
It will be great if we can build single file binary executable (the common format Prometheus exporters are available) from the source code.  I have tried building but my .net skills are not sufficient to build a single file Linux executable

### Specification
- Please build single file binary executable or add documentation to build them for Linux.

**Comment by tomkerkhove** [comment]
Thanks for the suggestions - We don't have any concrete plans at this point in time since we're mainly focussing on Docker but will keep it open to see what the demand is.

**Comment by tomkerkhove** [comment]
We are not planning to support this for now.
