### ISSUE TITLE
Not able to get promitor running

### ISSUE THREAD

**Issue by nairprakash** [tomkerkhove/promitor#958]
I am not sure this is related to a config issue, could you please share a copy of configuration that is known to be working. I keep getting the following from docker logs <containerID>.

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.RestClient.RestClientBuilder.WithEnvironment(AzureEnvironment environment)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.AzureConfigurable`1.BuildRestClient(AzureCredentials credentials)
>    at Microsoft.Azure.Management.Fluent.Azure.Configurable.Microsoft.Azure.Management.Fluent.Azure.IConfigurable.Authenticate(AzureCredentials credentials)
>    at Promitor.Integrations.AzureMonitor.AzureMonitorClient.CreateAzureClient(AzureEnvironment azureCloud, String tenantId, String subscriptionId, String applicationId, String applica
> tionSecret, IOptions`1 azureMonitorLoggingConfiguration, ILoggerFactory loggerFactory, IRuntimeMetricsCollector runtimeMetricsCollector) in /src/Promitor.Integrations.AzureMonitor/Azu
> reMonitorClient.cs:line 236
>    at Promitor.Integrations.AzureMonitor.AzureMonitorClient..ctor(AzureEnvironment azureCloud, String tenantId, String subscriptionId, String applicationId, String applicationSecret, 
> IOptions`1 azureMonitorLoggingConfiguration, IRuntimeMetricsCollector runtimeMetricsCollector, ILoggerFactory loggerFactory) in /src/Promitor.Integrations.AzureMonitor/AzureMonitorCli
> ent.cs:line 49
>    at Promitor.Scraper.Host.Extensions.IServiceCollectionExtensions.ConfigureAzureMonitorClient(MetricsDeclaration metricsDeclaration, IRuntimeMetricsCollector runtimeMetricCollector,
>  IConfiguration configuration, IOptions`1 azureMonitorLoggingConfiguration, ILoggerFactory loggerFactory) in /src/Promitor.Scraper.Host/IServiceCollectionExtensions.cs:line 84
>    at Promitor.Scraper.Host.Extensions.IServiceCollectionExtensions.ScheduleMetricScraping(IServiceCollection services) in /src/Promitor.Scraper.Host/IServiceCollectionExtensions.cs:l
> ine 50
>    at Promitor.Scraper.Host.Startup.ConfigureServices(IServiceCollection services) in /src/Promitor.Scraper.Host/Startup.cs:line 48
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
>    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()
>    at Promitor.Scraper.Host.Program.Main(String[] args) in /src/Promitor.Scraper.Host/Program.cs:line 25

**Comment by tomkerkhove** [comment]
Sure, happy to help. Would you mind sharing your runtime configuration along your metric declaration please?

In terms of samples, you can find some here:
- [`metric-config.yaml`](https://github.com/tomkerkhove/promitor/blob/master/src/metric-config.yaml)
- [`runtime-config.yaml`](https://github.com/tomkerkhove/promitor/blob/master/src/runtime-config.yaml)

**Comment by nairprakash** [comment]
Metric-declaration.yaml

version: v1
azureMetadata:
  tenantId:  <tenantId>
  subscriptionId:  <subscriptionId>
  applicationId:  <applicationId>
  applicationSecret:  <applicationSecret>
  resourceGroupName: <resource group name>
  cloud: eastus
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"

metrics:
  - name: azure_storage_account_capacity
    description: "The average capacity used in the storage account"
    resourceType: StorageAccount
    azureMetricConfiguration:
      metricName: UsedCapacity
      aggregation:
        type: Average
    resources:
    - accountName: <StorageAccount>

======================================================

runtime.yaml

server:
  httpPort: 80 # Optional. Default: 80
prometheus:
  metricUnavailableValue: NaN # Optional. Default: NaN
  enableMetricTimestamps: true # Optional. Default: true
  scrapeEndpoint:
    baseUriPath: /metrics # Optional. Default: /metrics
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml # Optional. Default:
/config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC # Optional. Note: Required to be specified when
turned on
    isEnabled: false # Optional. Default: false
    verbosity: trace # Optional. Default: N/A
  containerLogs:
    isEnabled: true # Optional. Default: true
    verbosity: trace # Optional. Default: N/A
  defaultVerbosity: error # Optional. Default: error

**Comment by tomkerkhove** [comment]
In terms of metric config, no need to provide application id and secret as those should be in environment variables, see https://promitor.io/configuration/v1.x/metrics/ & https://promitor.io/configuration/v1.x/azure-monitor

You'll need to fix that.

Also are you correctly mounting these files to the right location?

**Comment by nairprakash** [comment]
Yes, I am following the docker instructions.
inside the container they will be at /config  directory.

Also could you provide a "how to" to get list of definitions and namespaces
in order to know the metrics are being collected from the specified
subscriptions/resourcegroups.

Best Regards,
Prakash

**Comment by tomkerkhove** [comment]
What are you looking for exactly? The metrics you can scrape made available by Azure Monitor?

**Comment by nairprakash** [comment]
Hi Tom,

I got the container running and was able to get metrics into prometheus.
Thank you for your help.

One more question, how would we specify multiple dimensions for a given
metric?
example kube_node_status_condition  has 4 dimensions
condition,status,status2,node

- name: azure_kube_pod_status_phase
    description: "Number of pods by phase"
    resourceType: Generic
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: kube_pod_status_phase
      dimension:
        name: namespace
      aggregation:
        type: Average
    resources:
    - resourceUri: Microsoft.ContainerService/managedClusters

Regards
Prakash

**Comment by tomkerkhove** [comment]
For now you can only specify one dimension per metric, feel free to open a new issue with a small description of what it would allow you to do!

You can, however, add multiple metrics with each their own dimension; but they have to have a different name.

Ok if we close this issue since you're up and running?

**Comment by nairprakash** [comment]
Please goahead and close this issue.
